-- 0009_allergy_checks.sql
-- ალერგიის შემოწმება დანიშნულებისას: ალერგიის ტიპი (ალერგია/აუტანლობა), ალერგენული ჯგუფები,
-- ჯვარედინი რეაქციები, override-ის ჩანაწერი. საწყისი სია — needs_review=TRUE: საჭიროებს
-- კლინიკის ფარმაკოლოგის/სამედიცინო კონსულტანტის დამტკიცებას (POST /allergen-groups/:code/approve).

ALTER TABLE patient_allergies ADD COLUMN allergy_type VARCHAR(20) NOT NULL DEFAULT 'allergy'
    CHECK (allergy_type IN ('allergy', 'intolerance'));
-- სიმძიმე აღარ ივსება ავტომატურად 'severe'-ით — სავალდებულოა ცხადად მითითება
ALTER TABLE patient_allergies ALTER COLUMN severity DROP DEFAULT;
ALTER TABLE patient_allergies ADD CONSTRAINT chk_allergy_severity CHECK (severity IN ('mild', 'moderate', 'severe'));
ALTER TABLE patient_allergies ADD COLUMN deactivated_reason TEXT;

CREATE TABLE allergen_groups (
    code         VARCHAR(50) PRIMARY KEY CHECK (code ~ '^[A-Z0-9_]+$'),
    name         TEXT NOT NULL,
    needs_review BOOLEAN NOT NULL DEFAULT TRUE,
    reviewed_by  UUID REFERENCES users(id),
    reviewed_at  TIMESTAMPTZ
);
CREATE TABLE allergen_group_terms (
    group_code  VARCHAR(50) NOT NULL REFERENCES allergen_groups(code) ON DELETE CASCADE,
    term        CITEXT NOT NULL CHECK (length(term) >= 3),   -- ფუძე: შეიძლება იყოს სახელის ნაწილი
    PRIMARY KEY (group_code, term)
);
CREATE TABLE allergen_cross_reactivity (
    group_a  VARCHAR(50) NOT NULL REFERENCES allergen_groups(code) ON DELETE CASCADE,
    group_b  VARCHAR(50) NOT NULL REFERENCES allergen_groups(code) ON DELETE CASCADE,
    PRIMARY KEY (group_a, group_b),
    CHECK (group_a < group_b)
);

-- დანიშნულებაზე: რა გაფრთხილება ნახა ექიმმა და რატომ გადალახა
ALTER TABLE prescriptions
    ADD COLUMN allergy_alert_level     VARCHAR(20) NOT NULL DEFAULT 'none'
        CHECK (allergy_alert_level IN ('none', 'info', 'warning', 'warning_reason', 'block')),
    ADD COLUMN allergy_matches         JSONB,
    ADD COLUMN allergy_override_reason TEXT,
    ADD COLUMN allergy_override_by     UUID REFERENCES users(id),
    ADD CONSTRAINT chk_rx_allergy_override CHECK (
        allergy_alert_level NOT IN ('warning_reason', 'block')
        OR (allergy_override_reason IS NOT NULL AND allergy_override_by IS NOT NULL));

INSERT INTO allergen_groups (code, name) VALUES
  ('PENICILLINS', 'პენიცილინები'),
  ('CEPHALOSPORINS', 'ცეფალოსპორინები'),
  ('CARBAPENEMS', 'კარბაპენემები'),
  ('SULFONAMIDES', 'სულფანილამიდები (ანტიბაქტერიული)'),
  ('NSAIDS', 'არასტეროიდული ანთების საწინააღმდეგო (NSAID)'),
  ('MACROLIDES', 'მაკროლიდები'),
  ('FLUOROQUINOLONES', 'ფტორქინოლონები'),
  ('TETRACYCLINES', 'ტეტრაციკლინები'),
  ('IODINATED_CONTRAST', 'იოდშემცველი კონტრასტი'),
  ('LOCAL_ANESTH_AMIDE', 'ადგილობრივი ანესთეტიკები (ამიდური)'),
  ('LOCAL_ANESTH_ESTER', 'ადგილობრივი ანესთეტიკები (ეთერული)'),
  ('AROMATIC_ANTIEPILEPTICS', 'არომატული ანტიეპილეფსიური'),
  ('ACE_INHIBITORS', 'აგფ ინჰიბიტორები');

INSERT INTO allergen_group_terms (group_code, term) VALUES
  ('PENICILLINS', 'პენიცილინ'),
  ('PENICILLINS', 'ბენზილპენიცილინ'),
  ('PENICILLINS', 'ფენოქსიმეთილპენიცილინ'),
  ('PENICILLINS', 'ამოქსიცილინ'),
  ('PENICILLINS', 'ამპიცილინ'),
  ('PENICILLINS', 'ოქსაცილინ'),
  ('PENICILLINS', 'პიპერაცილინ'),
  ('PENICILLINS', 'ბიცილინ'),
  ('PENICILLINS', 'ექსტენცილინ'),
  ('PENICILLINS', 'ამოქსიკლავ'),
  ('PENICILLINS', 'აუგმენტინ'),
  ('PENICILLINS', 'ფლემოქსინ'),
  ('PENICILLINS', 'penicillin'),
  ('PENICILLINS', 'amoxicillin'),
  ('PENICILLINS', 'ampicillin'),
  ('PENICILLINS', 'oxacillin'),
  ('PENICILLINS', 'piperacillin'),
  ('PENICILLINS', 'amoxiclav'),
  ('PENICILLINS', 'augmentin'),
  ('CEPHALOSPORINS', 'ცეფ'),
  ('CEPHALOSPORINS', 'ცეფალოსპორინ'),
  ('CEPHALOSPORINS', 'cef'),
  ('CEPHALOSPORINS', 'ceph'),
  ('CARBAPENEMS', 'მეროპენემ'),
  ('CARBAPENEMS', 'იმიპენემ'),
  ('CARBAPENEMS', 'ერტაპენემ'),
  ('CARBAPENEMS', 'კარბაპენემ'),
  ('CARBAPENEMS', 'meropenem'),
  ('CARBAPENEMS', 'imipenem'),
  ('CARBAPENEMS', 'ertapenem'),
  ('SULFONAMIDES', 'სულფამეთოქსაზოლ'),
  ('SULFONAMIDES', 'კო-ტრიმოქსაზოლ'),
  ('SULFONAMIDES', 'კოტრიმოქსაზოლ'),
  ('SULFONAMIDES', 'ბისეპტოლ'),
  ('SULFONAMIDES', 'ბაქტრიმ'),
  ('SULFONAMIDES', 'სულფასალაზინ'),
  ('SULFONAMIDES', 'სულფანილამიდ'),
  ('SULFONAMIDES', 'sulfamethoxazole'),
  ('SULFONAMIDES', 'co-trimoxazole'),
  ('SULFONAMIDES', 'cotrimoxazole'),
  ('SULFONAMIDES', 'bactrim'),
  ('SULFONAMIDES', 'biseptol'),
  ('SULFONAMIDES', 'sulfasalazine'),
  ('NSAIDS', 'იბუპროფენ'),
  ('NSAIDS', 'დიკლოფენაკ'),
  ('NSAIDS', 'კეტოპროფენ'),
  ('NSAIDS', 'დექსკეტოპროფენ'),
  ('NSAIDS', 'კეტოროლაკ'),
  ('NSAIDS', 'ნაპროქსენ'),
  ('NSAIDS', 'ნიმესულიდ'),
  ('NSAIDS', 'მელოქსიკამ'),
  ('NSAIDS', 'ინდომეტაცინ'),
  ('NSAIDS', 'ასპირინ'),
  ('NSAIDS', 'აცეტილსალიცილ'),
  ('NSAIDS', 'ibuprofen'),
  ('NSAIDS', 'diclofenac'),
  ('NSAIDS', 'ketoprofen'),
  ('NSAIDS', 'ketorolac'),
  ('NSAIDS', 'naproxen'),
  ('NSAIDS', 'nimesulide'),
  ('NSAIDS', 'meloxicam'),
  ('NSAIDS', 'indomethacin'),
  ('NSAIDS', 'aspirin'),
  ('NSAIDS', 'acetylsalicylic'),
  ('MACROLIDES', 'აზითრომიცინ'),
  ('MACROLIDES', 'კლარითრომიცინ'),
  ('MACROLIDES', 'ერითრომიცინ'),
  ('MACROLIDES', 'azithromycin'),
  ('MACROLIDES', 'clarithromycin'),
  ('MACROLIDES', 'erythromycin'),
  ('FLUOROQUINOLONES', 'ციპროფლოქსაცინ'),
  ('FLUOROQUINOLONES', 'ლევოფლოქსაცინ'),
  ('FLUOROQUINOLONES', 'მოქსიფლოქსაცინ'),
  ('FLUOROQUINOLONES', 'ოფლოქსაცინ'),
  ('FLUOROQUINOLONES', 'ciprofloxacin'),
  ('FLUOROQUINOLONES', 'levofloxacin'),
  ('FLUOROQUINOLONES', 'moxifloxacin'),
  ('FLUOROQUINOLONES', 'ofloxacin'),
  ('TETRACYCLINES', 'ტეტრაციკლინ'),
  ('TETRACYCLINES', 'დოქსიციკლინ'),
  ('TETRACYCLINES', 'მინოციკლინ'),
  ('TETRACYCLINES', 'tetracycline'),
  ('TETRACYCLINES', 'doxycycline'),
  ('TETRACYCLINES', 'minocycline'),
  ('IODINATED_CONTRAST', 'იოდშემცველი კონტრასტ'),
  ('IODINATED_CONTRAST', 'იოდის შემცველი კონტრასტ'),
  ('IODINATED_CONTRAST', 'იოჰექსოლ'),
  ('IODINATED_CONTRAST', 'ომნიპაკ'),
  ('IODINATED_CONTRAST', 'იოპრომიდ'),
  ('IODINATED_CONTRAST', 'ულტრავისტ'),
  ('IODINATED_CONTRAST', 'იოდიქსანოლ'),
  ('IODINATED_CONTRAST', 'ვიზიპაკ'),
  ('IODINATED_CONTRAST', 'iohexol'),
  ('IODINATED_CONTRAST', 'omnipaque'),
  ('IODINATED_CONTRAST', 'iopromide'),
  ('IODINATED_CONTRAST', 'ultravist'),
  ('IODINATED_CONTRAST', 'iodixanol'),
  ('IODINATED_CONTRAST', 'visipaque'),
  ('LOCAL_ANESTH_AMIDE', 'ლიდოკაინ'),
  ('LOCAL_ANESTH_AMIDE', 'არტიკაინ'),
  ('LOCAL_ANESTH_AMIDE', 'ბუპივაკაინ'),
  ('LOCAL_ANESTH_AMIDE', 'მეპივაკაინ'),
  ('LOCAL_ANESTH_AMIDE', 'ულტრაკაინ'),
  ('LOCAL_ANESTH_AMIDE', 'lidocaine'),
  ('LOCAL_ANESTH_AMIDE', 'articaine'),
  ('LOCAL_ANESTH_AMIDE', 'bupivacaine'),
  ('LOCAL_ANESTH_AMIDE', 'mepivacaine'),
  ('LOCAL_ANESTH_ESTER', 'ნოვოკაინ'),
  ('LOCAL_ANESTH_ESTER', 'პროკაინ'),
  ('LOCAL_ANESTH_ESTER', 'ბენზოკაინ'),
  ('LOCAL_ANESTH_ESTER', 'ტეტრაკაინ'),
  ('LOCAL_ANESTH_ESTER', 'novocaine'),
  ('LOCAL_ANESTH_ESTER', 'procaine'),
  ('LOCAL_ANESTH_ESTER', 'benzocaine'),
  ('LOCAL_ANESTH_ESTER', 'tetracaine'),
  ('AROMATIC_ANTIEPILEPTICS', 'კარბამაზეპინ'),
  ('AROMATIC_ANTIEPILEPTICS', 'ოქსკარბაზეპინ'),
  ('AROMATIC_ANTIEPILEPTICS', 'ფენიტოინ'),
  ('AROMATIC_ANTIEPILEPTICS', 'ლამოტრიჯინ'),
  ('AROMATIC_ANTIEPILEPTICS', 'ფენობარბიტალ'),
  ('AROMATIC_ANTIEPILEPTICS', 'carbamazepine'),
  ('AROMATIC_ANTIEPILEPTICS', 'oxcarbazepine'),
  ('AROMATIC_ANTIEPILEPTICS', 'phenytoin'),
  ('AROMATIC_ANTIEPILEPTICS', 'lamotrigine'),
  ('AROMATIC_ANTIEPILEPTICS', 'phenobarbital'),
  ('ACE_INHIBITORS', 'ენალაპრილ'),
  ('ACE_INHIBITORS', 'ლიზინოპრილ'),
  ('ACE_INHIBITORS', 'კაპტოპრილ'),
  ('ACE_INHIBITORS', 'პერინდოპრილ'),
  ('ACE_INHIBITORS', 'რამიპრილ'),
  ('ACE_INHIBITORS', 'ფოზინოპრილ'),
  ('ACE_INHIBITORS', 'enalapril'),
  ('ACE_INHIBITORS', 'lisinopril'),
  ('ACE_INHIBITORS', 'captopril'),
  ('ACE_INHIBITORS', 'perindopril'),
  ('ACE_INHIBITORS', 'ramipril'),
  ('ACE_INHIBITORS', 'fosinopril');

INSERT INTO allergen_cross_reactivity (group_a, group_b) VALUES
  ('CEPHALOSPORINS', 'PENICILLINS'),
  ('CARBAPENEMS', 'PENICILLINS'),
  ('CARBAPENEMS', 'CEPHALOSPORINS');
