/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentStatus = "cancelled" | "checked_in" | "completed" | "confirmed" | "no_show" | "scheduled";

export type AuthProvider = "ldap" | "local";

export type EncounterStatus = "active" | "cancelled" | "discharged" | "planned";

export type EncounterType = "emergency" | "inpatient" | "outpatient";

export type GenderType = "female" | "male" | "other";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type ReferralStatus = "cancelled" | "completed" | "in_progress" | "requested";

export type ReferralType = "hospitalization" | "imaging" | "lab" | "specialist_consult";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Appointments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  department_id: string;
  doctor_id: string;
  encounter_id: string | null;
  id: Generated<string>;
  patient_id: string;
  reason: string | null;
  scheduled_end: Timestamp;
  scheduled_start: Timestamp;
  status: Generated<AppointmentStatus>;
}

export interface AuditLogs {
  action: string;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_name: string;
  id: Generated<Int8>;
  ip_address: string | null;
  new_data: Json | null;
  old_data: Json | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  ip_address: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface Departments {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface EncounterDiagnoses {
  comment: string | null;
  created_at: Generated<Timestamp>;
  diagnosed_by: string | null;
  diagnosis_type: string;
  encounter_id: string;
  icd10_code: string;
  icd10_title: string;
  id: Generated<string>;
}

export interface EncounterPaymentOverrides {
  approved_by: string;
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  reason: string;
}

export interface Encounters {
  attending_doctor_id: string | null;
  chief_complaint: string | null;
  created_at: Generated<Timestamp>;
  department_id: string;
  end_time: Timestamp | null;
  history_of_present_illness: string | null;
  id: Generated<string>;
  objective_status: string | null;
  patient_id: string;
  start_time: Generated<Timestamp>;
  status: Generated<EncounterStatus>;
  type: EncounterType;
  updated_at: Generated<Timestamp>;
}

export interface EncounterVitals {
  bmi: Generated<Numeric | null>;
  diastolic_bp: number | null;
  encounter_id: string;
  heart_rate: number | null;
  height_cm: Numeric | null;
  id: Generated<string>;
  recorded_at: Generated<Timestamp>;
  respiratory_rate: number | null;
  spo2: number | null;
  systolic_bp: number | null;
  taken_by: string | null;
  temperature: Numeric | null;
  weight_kg: Numeric | null;
}

export interface GeneratedDocuments {
  document_type: string;
  encounter_id: string;
  file_path: string;
  generated_at: Generated<Timestamp>;
  generated_by: string | null;
  id: Generated<string>;
  verification_token: Generated<string>;
}

export interface Icd10Chapters {
  code_from: string;
  code_to: string;
  id: number;
  title: string;
}

export interface Icd10Codes {
  category: Generated<string | null>;
  chapter_id: number | null;
  code: string;
  is_active: Generated<boolean>;
  is_asterisk: Generated<boolean>;
  is_dagger: Generated<boolean>;
  needs_review: Generated<boolean>;
  title: string;
}

export interface InvoiceLineItems {
  adjusted_by: string | null;
  description: string;
  discount_reason: string | null;
  id: Generated<string>;
  invoice_id: string;
  line_total: Generated<Numeric | null>;
  original_price: Numeric | null;
  quantity: Generated<number>;
  referral_id: string | null;
  tariff_id: string | null;
  unit_price: Numeric;
}

export interface Invoices {
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  insurance_share: Generated<Numeric>;
  invoice_number: string;
  paid_status: Generated<string>;
  patient_share: Numeric;
  state_share: Generated<Numeric>;
  total_amount: Numeric;
}

export interface PatientAllergies {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  patient_id: string;
  reaction_type: string | null;
  recorded_by: string | null;
  severity: Generated<string>;
  substance: string;
}

export interface PatientChronicConditions {
  condition_name: string;
  created_at: Generated<Timestamp>;
  icd10_code: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  patient_id: string;
  recorded_by: string | null;
}

export interface Patients {
  address: string | null;
  birth_date: string;
  blood_group: string | null;
  citizenship: Generated<string>;
  created_at: Generated<Timestamp>;
  death_datetime: Timestamp | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  first_name: string;
  gender: GenderType;
  id: Generated<string>;
  is_deceased: Generated<boolean>;
  last_name: string;
  passport_number: string | null;
  personal_number: string | null;
  phone_number: string;
  updated_at: Generated<Timestamp>;
}

export interface Payments {
  amount: Numeric;
  id: Generated<string>;
  invoice_id: string;
  method: string;
  paid_at: Generated<Timestamp>;
  received_by: string | null;
  terminal_ref: string | null;
}

export interface Prescriptions {
  created_at: Generated<Timestamp>;
  dosage: string;
  duration_days: number | null;
  encounter_id: string;
  frequency: string;
  id: Generated<string>;
  instructions: string | null;
  medication_name: string;
  prescribed_by: string;
  route: string;
}

export interface Referrals {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  reason: string;
  requested_by: string;
  result_text: string | null;
  status: Generated<ReferralStatus>;
  target_department_id: string | null;
  type: ReferralType;
}

export interface ReferralTypeTariffs {
  tariff_id: string;
  type: ReferralType;
}

export interface ServiceTariffs {
  base_price: Numeric;
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  title: string;
}

export interface Users {
  auth_provider: Generated<AuthProvider>;
  consultation_tariff_id: string | null;
  created_at: Generated<Timestamp>;
  department_id: string | null;
  email: string;
  failed_login_count: Generated<number>;
  first_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  last_name: string;
  ldap_username: string | null;
  license_number: string | null;
  locked_until: Timestamp | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Timestamp | null;
  password_hash: string | null;
  personal_number: string;
  phone: string | null;
  role: string;
  signature_file_path: string | null;
  specialty: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  appointments: Appointments;
  audit_logs: AuditLogs;
  auth_sessions: AuthSessions;
  departments: Departments;
  encounter_diagnoses: EncounterDiagnoses;
  encounter_payment_overrides: EncounterPaymentOverrides;
  encounter_vitals: EncounterVitals;
  encounters: Encounters;
  generated_documents: GeneratedDocuments;
  icd10_chapters: Icd10Chapters;
  icd10_codes: Icd10Codes;
  invoice_line_items: InvoiceLineItems;
  invoices: Invoices;
  patient_allergies: PatientAllergies;
  patient_chronic_conditions: PatientChronicConditions;
  patients: Patients;
  payments: Payments;
  prescriptions: Prescriptions;
  referral_type_tariffs: ReferralTypeTariffs;
  referrals: Referrals;
  service_tariffs: ServiceTariffs;
  users: Users;
}
