/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentStatus = "cancelled" | "checked_in" | "completed" | "confirmed" | "no_show" | "scheduled";

export type AuthProvider = "ldap" | "local";

export type EncounterStatus = "active" | "cancelled" | "discharged" | "planned";

export type EncounterType = "emergency" | "inpatient" | "outpatient";

export type GenderType = "female" | "male" | "other";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type ReferralStatus = "cancelled" | "completed" | "in_progress" | "requested";

export type ReferralType = "hospitalization" | "imaging" | "lab" | "specialist_consult";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AddressUnits {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  parent_code: string | null;
  region: string;
  type: string;
}

export interface AllergenCrossReactivity {
  group_a: string;
  group_b: string;
}

export interface AllergenGroups {
  code: string;
  name: string;
  needs_review: Generated<boolean>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
}

export interface AllergenGroupTerms {
  group_code: string;
  term: string;
}

export interface Appointments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  department_id: string;
  doctor_id: string;
  encounter_id: string | null;
  id: Generated<string>;
  patient_id: string;
  reason: string | null;
  scheduled_end: Timestamp;
  scheduled_start: Timestamp;
  status: Generated<AppointmentStatus>;
}

export interface AuditLogs {
  action: string;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_name: string;
  id: Generated<Int8>;
  ip_address: string | null;
  new_data: Json | null;
  old_data: Json | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  ip_address: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface ClinicSettings {
  address: string;
  consent_methods: Generated<string[]>;
  director_name: string;
  director_title: Generated<string>;
  email: string | null;
  id: Generated<number>;
  name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ConsentTypes {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  scope: string;
  sort_order: Generated<number>;
}

export interface ConsentTypeVersions {
  body_text: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  text_approved: Generated<boolean>;
  type_code: string;
  version: number;
}

export interface Departments {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface DocumentCounters {
  document_type: string;
  last_value: Generated<number>;
  year: number;
}

export interface DxDevices {
  ae_title: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  modalities: string[];
  name: string;
  room: string | null;
  section: Generated<string>;
  slot_minutes: Generated<number>;
  sort_order: Generated<number>;
  work_end: Generated<string>;
  work_start: Generated<string>;
}

export interface DxImages {
  caption: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  deactivated_reason: string | null;
  file_path: string;
  id: Generated<string>;
  in_report: Generated<boolean>;
  is_active: Generated<boolean>;
  mime_type: string;
  order_item_id: string;
  sha256: string;
  size_bytes: number;
  sort_order: Generated<number>;
  source: string;
}

export interface DxItemFiles {
  filename: string;
  id: Generated<string>;
  mail_file_id: string | null;
  mime: string;
  order_item_id: string;
  remove_reason: string | null;
  removed_at: Timestamp | null;
  removed_by: string | null;
  sha256: string | null;
  size_bytes: number | null;
  source: string;
  storage_path: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string | null;
}

export interface DxOrderItems {
  accession_number: string | null;
  allergy_override_reason: string | null;
  arrived_at: Timestamp | null;
  arrived_by: string | null;
  blank_version_id: string | null;
  cancel_reason: string | null;
  clinical_note: string | null;
  collection_issue: string | null;
  collection_issue_at: Timestamp | null;
  contrast_agent: string | null;
  contrast_volume_ml: Numeric | null;
  device_id: string | null;
  dose_text: string | null;
  encounter_id: string;
  ext_cost: Numeric | null;
  ext_due_at: Timestamp | null;
  ext_lab_id: string | null;
  ext_result_at: Timestamp | null;
  ext_result_by: string | null;
  ext_result_name: string | null;
  ext_result_path: string | null;
  ext_shipment_id: string | null;
  id: Generated<string>;
  lab_method_id: string | null;
  ordered_at: Generated<Timestamp>;
  ordered_by: string;
  patient_id: string;
  performed_at: Timestamp | null;
  pregnancy_weeks: number | null;
  priority: Generated<string>;
  report_text: string | null;
  resulted_at: Timestamp | null;
  resulted_by: string | null;
  safety: Json | null;
  scheduled_by: string | null;
  scheduled_end: Timestamp | null;
  scheduled_start: Timestamp | null;
  section: string;
  service_id: string;
  specimen_id: string | null;
  status: Generated<string>;
  tech_note: string | null;
  technician_id: string | null;
  validated_at: Timestamp | null;
  validated_by: string | null;
  verify_token: string | null;
}

export interface DxReports {
  amend_reason: string | null;
  amended_at: Timestamp | null;
  amended_by: string | null;
  author_id: string | null;
  created_at: Generated<Timestamp>;
  critical_notified_at: Timestamp | null;
  critical_notified_to: string | null;
  findings: string | null;
  impression: string | null;
  is_critical: Generated<boolean>;
  order_item_id: string;
  recommendation: string | null;
  signed_at: Timestamp | null;
  signed_by: string | null;
  status: Generated<string>;
  technique: string | null;
  template_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DxReportTemplates {
  body: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  findings: string | null;
  id: Generated<string>;
  impression: string | null;
  is_active: Generated<boolean>;
  kind: Generated<string>;
  modality: string | null;
  name: string;
  owner_id: string | null;
  recommendation: string | null;
  section: string;
  service_id: string | null;
  sort_order: Generated<number>;
  target: string | null;
  technique: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DxReportVersions {
  amend_reason: string | null;
  critical_notified_to: string | null;
  findings: string | null;
  id: Generated<string>;
  impression: string;
  is_critical: boolean;
  order_item_id: string;
  recommendation: string | null;
  signed_at: Timestamp;
  signed_by: string;
  technique: string | null;
  version: number;
}

export interface DxServices {
  blank_template_id: string | null;
  body_part: string | null;
  code: string;
  container: string | null;
  contrast: string | null;
  default_method_id: string | null;
  duration_minutes: number | null;
  ext_turnaround_days: Generated<number>;
  external_lab: string | null;
  external_lab_id: string | null;
  group_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_micro: Generated<boolean>;
  modality: string | null;
  name: string;
  needs_review: Generated<boolean>;
  performed_by: Generated<string>;
  prep_instructions: string | null;
  purchase_price: Numeric | null;
  report_comment: string | null;
  section: string;
  sort_order: Generated<number>;
  specimen_type: string | null;
  tariff_id: string;
}

export interface EncounterDiagnoses {
  comment: string | null;
  created_at: Generated<Timestamp>;
  diagnosed_by: string | null;
  diagnosis_type: string;
  encounter_id: string;
  icd10_code: string;
  icd10_title: string;
  id: Generated<string>;
}

export interface EncounterPaymentOverrides {
  approved_by: string;
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  reason: string;
}

export interface Encounters {
  attending_doctor_id: string | null;
  chief_complaint: string | null;
  created_at: Generated<Timestamp>;
  department_id: string;
  end_time: Timestamp | null;
  external_referral: string | null;
  history_of_present_illness: string | null;
  id: Generated<string>;
  objective_status: string | null;
  patient_id: string;
  start_time: Generated<Timestamp>;
  status: Generated<EncounterStatus>;
  type: EncounterType;
  updated_at: Generated<Timestamp>;
  visit_kind: Generated<string>;
}

export interface EncounterVitals {
  bmi: Generated<Numeric | null>;
  diastolic_bp: number | null;
  encounter_id: string;
  heart_rate: number | null;
  height_cm: Numeric | null;
  id: Generated<string>;
  recorded_at: Generated<Timestamp>;
  respiratory_rate: number | null;
  spo2: number | null;
  systolic_bp: number | null;
  taken_by: string | null;
  temperature: Numeric | null;
  weight_kg: Numeric | null;
}

export interface EndoProcedures {
  allergies_reviewed: Generated<boolean>;
  anticoag_note: string | null;
  anticoagulants: string | null;
  asa_class: number | null;
  bbps_score: number | null;
  bowel_prep: string | null;
  checklist_at: Timestamp | null;
  checklist_by: string | null;
  checklist_note: string | null;
  complication_note: string | null;
  complications: Generated<string>;
  consent_confirmed: Generated<boolean>;
  discharged_at: Timestamp | null;
  ended_at: Timestamp | null;
  extent_reached: string | null;
  fasting_hours: Numeric | null;
  interventions: Generated<Json>;
  monitoring: Generated<Json>;
  nurse_id: string | null;
  order_item_id: string;
  recovery_score: number | null;
  scope_id: string | null;
  scope_used_at: Timestamp | null;
  sedation_by: string | null;
  sedation_drugs: Generated<Json>;
  sedation_type: string | null;
  started_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  withdrawal_minutes: Numeric | null;
}

export interface EndoReprocessing {
  disinfectant: string | null;
  id: Generated<string>;
  leak_test: boolean;
  machine: string | null;
  method: string;
  note: string | null;
  performed_at: Generated<Timestamp>;
  performed_by: string;
  result: string;
  scope_id: string;
}

export interface EndoScopes {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  note: string | null;
  scope_type: string;
  serial_number: string;
}

export interface Expenses {
  amount: Numeric;
  category: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  department_id: string | null;
  description: string | null;
  doc_number: string | null;
  expense_date: string;
  id: Generated<string>;
  is_void: Generated<boolean>;
  payment_method: Generated<string>;
  supplier: string | null;
  updated_at: Generated<Timestamp>;
  void_reason: string | null;
}

export interface GeneratedDocuments {
  document_number: string | null;
  document_type: string;
  encounter_id: string;
  file_path: string;
  file_sha256: string | null;
  generated_at: Generated<Timestamp>;
  generated_by: string | null;
  id: Generated<string>;
  payload: Generated<Json>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  status: Generated<string>;
  verification_token: Generated<string>;
}

export interface Icd10Chapters {
  code_from: string;
  code_to: string;
  id: number;
  title: string;
}

export interface Icd10Codes {
  category: Generated<string | null>;
  chapter_id: number | null;
  code: string;
  is_active: Generated<boolean>;
  is_asterisk: Generated<boolean>;
  is_dagger: Generated<boolean>;
  needs_review: Generated<boolean>;
  title: string;
}

export interface InvoiceLineItems {
  adjusted_by: string | null;
  description: string;
  discount_reason: string | null;
  dx_order_item_id: string | null;
  id: Generated<string>;
  invoice_id: string;
  line_total: Generated<Numeric | null>;
  original_price: Numeric | null;
  quantity: Generated<number>;
  referral_id: string | null;
  stock_doc_line_id: string | null;
  tariff_id: string | null;
  unit_price: Numeric;
}

export interface Invoices {
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  insurance_share: Generated<Numeric>;
  invoice_number: string;
  paid_status: Generated<string>;
  patient_share: Numeric;
  state_share: Generated<Numeric>;
  total_amount: Numeric;
}

export interface LabAnalytes {
  code: string;
  critical_high: Numeric | null;
  critical_low: Numeric | null;
  decimals: number | null;
  delta_limit_pct: Numeric | null;
  delta_window_days: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  norm_version: Generated<number>;
  options: string | null;
  result_type: string;
  service_id: string;
  sort_order: Generated<number>;
  unit: Generated<string>;
}

export interface LabBlankGroupAssignments {
  group_name: string;
  template_id: string;
}

export interface LabBlankImages {
  data: Buffer;
  height: number;
  id: Generated<string>;
  mime: string;
  sha256: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string | null;
  width: number;
}

export interface LabBlankTemplates {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  current_version: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_default: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface LabBlankVersions {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  settings: Json;
  template_id: string;
  version: number;
}

export interface LabDeliverySettings {
  auto_send: Generated<boolean>;
  email_body: Generated<string>;
  email_subject: Generated<string>;
  enabled: Generated<boolean>;
  encrypt_pdf: Generated<boolean>;
  id: Generated<number>;
  sms_email_sent: Generated<string>;
  sms_ready: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface LabExternalLabs {
  contact_person: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  emails: Generated<string[]>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  mail_id_regex: string | null;
  mail_match_patient: Generated<boolean>;
  mail_match_window_days: Generated<number>;
  name: string;
  note: string | null;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LabExtMail {
  from_addr: string | null;
  id: Generated<string>;
  lab_id: string | null;
  message_id: string;
  note: string | null;
  received_at: Generated<Timestamp>;
  sent_at: Timestamp | null;
  source: Generated<string>;
  status: string;
  subject: string | null;
  uploaded_by: string | null;
}

export interface LabExtMailFiles {
  barcode: string | null;
  candidates: Json | null;
  filename: string;
  id: Generated<string>;
  item_ids: Generated<string[]>;
  mail_id: string;
  match_method: string | null;
  mime: string;
  reason: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  service_code: string | null;
  sha256: string | null;
  size_bytes: number;
  status: string;
  storage_path: string | null;
}

export interface LabExtMailState {
  checked_at: Timestamp | null;
  error: string | null;
  id: Generated<number>;
  ok: boolean | null;
  processed_total: Generated<number>;
}

export interface LabExtSettlements {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  invoice_no: string | null;
  items_count: number;
  lab_id: string;
  note: string | null;
  paid_at: string | null;
  period: string;
}

export interface LabExtShipments {
  courier: string | null;
  id: Generated<string>;
  lab_id: string;
  note: string | null;
  sent_at: Generated<Timestamp>;
  sent_by: string | null;
  shipment_no: string;
}

export interface LabGatewayAlerts {
  id: Generated<Int8>;
  instrument_id: string | null;
  kind: string;
  message: string;
  notified: Json | null;
  notified_resolved: Json | null;
  resolved_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface LabGatewayAlertSettings {
  disconnect_minutes: Generated<number>;
  emails: Generated<string[]>;
  enabled: Generated<boolean>;
  id: Generated<number>;
  notify_resolved: Generated<boolean>;
  silent_minutes: Generated<number>;
  sms_phones: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  work_days: Generated<number[]>;
  work_end: Generated<string>;
  work_start: Generated<string>;
}

export interface LabGatewayCommands {
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  instrument_id: string | null;
  kind: string;
  params: Generated<Json>;
  requested_by: string | null;
  result: Json | null;
  status: Generated<string>;
}

export interface LabGatewayState {
  heartbeat_at: Timestamp;
  hostname: string | null;
  id: Generated<number>;
  started_at: Timestamp;
  version: string | null;
}

export interface LabInstrumentCodes {
  analyte_id: string | null;
  code: string;
  factor: Generated<Numeric>;
  id: Generated<string>;
  instrument_id: string;
  send_order: Generated<boolean>;
  service_id: string | null;
}

export interface LabInstrumentMessages {
  created_at: Generated<Timestamp>;
  direction: string;
  error: string | null;
  id: Generated<Int8>;
  instrument_id: string;
  kind: string;
  raw: string;
  summary: string | null;
}

export interface LabInstrumentOrders {
  attempts: Generated<number>;
  codes: string[];
  created_at: Generated<Timestamp>;
  error: string | null;
  id: Generated<Int8>;
  instrument_id: string;
  sent_at: Timestamp | null;
  specimen_id: string;
  status: Generated<string>;
}

export interface LabInstrumentResults {
  analyte_id: string | null;
  barcode: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  flags: string | null;
  id: Generated<Int8>;
  instrument_id: string;
  measured_at: Timestamp | null;
  message_id: Int8 | null;
  order_item_id: string | null;
  processed_at: Timestamp | null;
  reason: string | null;
  rerun: Generated<boolean>;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  result_status: string | null;
  status: Generated<string>;
  unit: string | null;
  value: string | null;
}

export interface LabInstruments {
  alerts_enabled: Generated<boolean>;
  conn_mode: string;
  created_at: Generated<Timestamp>;
  down_since: Timestamp | null;
  host: string | null;
  id: Generated<string>;
  is_enabled: Generated<boolean>;
  last_error: string | null;
  last_message_at: Timestamp | null;
  listen_only: Generated<boolean>;
  method_id: string;
  order_mode: Generated<string>;
  peer: string | null;
  port: number;
  protocol: string;
  settings: Generated<Json>;
  silent_minutes: number | null;
  status: Generated<string>;
  status_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface LabInstrumentSeenCodes {
  code: string;
  first_seen: Generated<Timestamp>;
  instrument_id: string;
  last_seen: Generated<Timestamp>;
  last_unit: string | null;
  last_value: string | null;
  seen_count: Generated<number>;
}

export interface LabMethods {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: Generated<string>;
  manufacturer: string | null;
  name: string;
  note: string | null;
  serial_number: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LabNormVersions {
  analyte_id: string;
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  critical_high: Numeric | null;
  critical_low: Numeric | null;
  id: Generated<string>;
  ranges: Json;
  reason: string;
  recalculated: Generated<number>;
  unit: Generated<string>;
  version: number;
}

export interface LabQcMaterials {
  barcode: string | null;
  created_at: Generated<Timestamp>;
  expires_on: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  level: string;
  lot: string;
  manufacturer: string | null;
  name: string;
}

export interface LabQcResults {
  created_at: Generated<Timestamp>;
  entered_by: string | null;
  exclude_reason: string | null;
  excluded_at: Timestamp | null;
  excluded_by: string | null;
  id: Generated<Int8>;
  instrument_result_id: Int8 | null;
  measured_at: Generated<Timestamp>;
  source: string;
  status: string;
  target_id: string;
  value: Numeric;
  violations: Generated<string[]>;
  z: Numeric;
}

export interface LabQcRules {
  action: string;
  analyte_id: string;
  rules: string[];
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface LabQcTargets {
  analyte_id: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  material_id: string;
  mean: Numeric;
  method_id: string;
  sd: Numeric;
}

export interface LabQcViolations {
  action: string;
  analyte_id: string;
  cause: string | null;
  corrective_action: string | null;
  id: Generated<Int8>;
  method_id: string;
  opened_at: Generated<Timestamp>;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  result_id: Int8;
  rules: string[];
  status: Generated<string>;
}

export interface LabReferenceRanges {
  age_max_days: Generated<number>;
  age_min_days: Generated<number>;
  analyte_id: string;
  high: Numeric | null;
  id: Generated<string>;
  low: Numeric | null;
  method_id: string | null;
  normal_text: string | null;
  pregnancy: string | null;
  sex: string | null;
}

export interface LabResultDeliveries {
  attachments: Generated<number>;
  channel: string;
  created_at: Generated<Timestamp>;
  encounter_id: string;
  error: string | null;
  id: Generated<Int8>;
  item_ids: Generated<string[]>;
  patient_id: string;
  recipient: string;
  sent_by: string | null;
  status: string;
  trigger: string;
}

export interface LabResultImages {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  instrument_id: string | null;
  kind: string;
  mime: string | null;
  order_item_id: string;
  points: Json | null;
  storage_path: string | null;
  title: string | null;
}

export interface LabResults {
  analyte_id: string;
  entered_at: Generated<Timestamp>;
  entered_by: string | null;
  flag: string | null;
  id: Generated<string>;
  instrument_id: string | null;
  norm_version: number | null;
  order_item_id: string;
  recalculated_at: Timestamp | null;
  ref_high: Numeric | null;
  ref_low: Numeric | null;
  ref_text: string | null;
  unit: Generated<string>;
  value_num: Numeric | null;
  value_text: string | null;
}

export interface LabSpecimens {
  barcode: string;
  collected_at: Generated<Timestamp>;
  collected_by: string | null;
  container: string | null;
  encounter_id: string;
  id: Generated<string>;
  patient_id: string;
  received_at: Timestamp | null;
  received_by: string | null;
  reject_reason: string | null;
  specimen_type: string;
  status: Generated<string>;
}

export interface MedDosageForms {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
}

export interface MedGenericAllergens {
  generic_id: string;
  group_code: string;
}

export interface MedGenerics {
  atc_code: string | null;
  controlled_class: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dose_per_unit: Numeric | null;
  dose_unit: string | null;
  form_code: string;
  high_alert: Generated<boolean>;
  id: Generated<string>;
  inn: string;
  inn_latin: string | null;
  is_active: Generated<boolean>;
  max_daily_dose: Numeric | null;
  max_single_dose: Numeric | null;
  min_age_days: number | null;
  notes: string | null;
  patient_only: Generated<boolean>;
  ped_max_daily_per_kg: Numeric | null;
  ped_max_single_per_kg: Numeric | null;
  reserve_antibiotic: Generated<boolean>;
  routes: Generated<string[]>;
  strength: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MedInteractions {
  a_atc: string | null;
  a_generic_id: string | null;
  b_atc: string | null;
  b_generic_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  effect: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  recommendation: string | null;
  severity: string;
  source: Generated<string>;
  source_ref: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MedRoutes {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
}

export interface MicroAntibiotics {
  class: string | null;
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
}

export interface MicroAst {
  antibiotic_id: string;
  interp: string | null;
  isolate_id: string;
  mic: string | null;
  reported: Generated<boolean>;
  reserve: Generated<boolean>;
  sort_order: Generated<number>;
  zone_mm: Numeric | null;
}

export interface MicroCultures {
  comment: string | null;
  gram_stain: string | null;
  growth_summary: string | null;
  id: Generated<string>;
  order_item_id: string;
  stage: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface MicroIsolates {
  comment: string | null;
  culture_id: string;
  id: Generated<string>;
  organism_id: string | null;
  panel_id: string | null;
  quantity: string | null;
  seq: number;
}

export interface MicroOrganisms {
  code: string;
  gram: string;
  group_code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
}

export interface MicroPanelItems {
  antibiotic_id: string;
  panel_id: string;
  reserve: Generated<boolean>;
  sort_order: Generated<number>;
}

export interface MicroPanels {
  code: string;
  group_code: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
}

export interface MicroReports {
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  issued_by: string | null;
  kind: string;
  order_item_id: string;
  snapshot: Json;
}

export interface PathRequests {
  clinical_info: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  external_lab: string | null;
  id: Generated<string>;
  order_item_id: string;
  patient_id: string;
  request_no: string;
  result_entered_by: string | null;
  result_file_path: string | null;
  result_received_at: Timestamp | null;
  result_text: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  sent_at: Timestamp | null;
  sent_by: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PathSpecimens {
  description: string | null;
  fixative: Generated<string>;
  id: Generated<string>;
  jar_no: number;
  pieces: Generated<number>;
  request_id: string;
  site: string;
}

export interface PatientAllergies {
  allergy_type: Generated<string>;
  created_at: Generated<Timestamp>;
  deactivated_reason: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  patient_id: string;
  reaction_type: string | null;
  recorded_by: string | null;
  severity: string;
  substance: string;
}

export interface PatientChronicConditions {
  condition_name: string;
  created_at: Generated<Timestamp>;
  icd10_code: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  patient_id: string;
  recorded_by: string | null;
}

export interface PatientConsents {
  decision: string;
  encounter_id: string | null;
  file_id: string;
  id: Generated<string>;
  method: string;
  patient_id: string;
  recorded_by: string;
  representative_id_number: string | null;
  representative_name: string | null;
  representative_relation: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  signed_at: Generated<Timestamp>;
  signer_type: string;
  type_code: string;
  version_id: string;
}

export interface PatientFiles {
  created_at: Generated<Timestamp>;
  deactivated_reason: string | null;
  doc_type: string;
  file_path: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  mime_type: string;
  note: string | null;
  original_name: string | null;
  patient_id: string;
  sha256: string;
  size_bytes: number;
  uploaded_by: string | null;
}

export interface Patients {
  address: string | null;
  address_country: string | null;
  address_district_code: string | null;
  address_line: string | null;
  address_unit_code: string | null;
  address_village: string | null;
  birth_date: string;
  blood_group: string | null;
  citizenship: Generated<string>;
  created_at: Generated<Timestamp>;
  death_datetime: Timestamp | null;
  email: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  first_name: string;
  gender: GenderType;
  id: Generated<string>;
  is_deceased: Generated<boolean>;
  last_name: string;
  passport_number: string | null;
  personal_number: string | null;
  phone_number: string;
  result_email: Generated<boolean>;
  result_sms: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface Payments {
  amount: Numeric;
  id: Generated<string>;
  invoice_id: string;
  method: string;
  paid_at: Generated<Timestamp>;
  received_by: string | null;
  terminal_ref: string | null;
}

export interface Prescriptions {
  allergy_alert_level: Generated<string>;
  allergy_matches: Json | null;
  allergy_override_by: string | null;
  allergy_override_reason: string | null;
  created_at: Generated<Timestamp>;
  dosage: string;
  duration_days: number | null;
  encounter_id: string;
  frequency: string;
  id: Generated<string>;
  instructions: string | null;
  medication_name: string;
  prescribed_by: string;
  route: string;
}

export interface Referrals {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  reason: string;
  requested_by: string;
  result_text: string | null;
  status: Generated<ReferralStatus>;
  target_department_id: string | null;
  type: ReferralType;
}

export interface ReferralTypeTariffs {
  tariff_id: string;
  type: ReferralType;
}

export interface Roles {
  capabilities: string[];
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_system: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ServiceTariffs {
  base_price: Numeric;
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  title: string;
}

export interface StockBalances {
  item_id: string;
  location_id: string;
  lot_id: string;
  qty: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface StockCategories {
  billing_mode: Generated<string>;
  code: string;
  created_at: Generated<Timestamp>;
  expiry_warn_days: number | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: string;
  markup_pct: Numeric | null;
  name: string;
  parent_id: string | null;
  requires_expiry: Generated<boolean>;
  requires_lot: Generated<boolean>;
  serial_tracked: Generated<boolean>;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface StockCountLines {
  count_id: string;
  counted_at: Timestamp | null;
  counted_by: string | null;
  counted_qty: Numeric | null;
  expected_qty: Generated<Numeric>;
  expires_on: string | null;
  id: Generated<string>;
  is_extra: Generated<boolean>;
  item_id: string;
  lot_id: string | null;
  lot_no: string | null;
  note: string | null;
  serial_no: string | null;
}

export interface StockCounts {
  adjustment_doc_id: string | null;
  approved_at: Timestamp | null;
  approved_by: string | null;
  blind: Generated<boolean>;
  category_id: string | null;
  count_no: string;
  id: Generated<string>;
  location_id: string;
  notes: string | null;
  reason: string | null;
  started_at: Generated<Timestamp>;
  started_by: string;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  updated_at: Generated<Timestamp>;
}

export interface StockDocLines {
  doc_id: string;
  expires_on: string | null;
  id: Generated<string>;
  item_id: string;
  line_net: Numeric | null;
  line_no: number;
  line_vat: Numeric | null;
  lot_id: string | null;
  lot_no: string | null;
  notes: string | null;
  override_reason: string | null;
  pack_id: string | null;
  pack_qty_base: Generated<Numeric>;
  patient_id: string | null;
  price: Numeric | null;
  produced_on: string | null;
  qty: Numeric;
  qty_base: Numeric;
  request_line_id: string | null;
  sale_price: Numeric | null;
  serial_no: string | null;
  short_expiry_reason: string | null;
  unit_cost: Numeric | null;
  vat_rate: Generated<Numeric>;
}

export interface StockDocs {
  approval_status: string | null;
  approved_at: Timestamp | null;
  approved_by: string | null;
  count_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_date: string;
  doc_no: string | null;
  doc_type: string;
  encounter_id: string | null;
  from_location_id: string | null;
  id: Generated<string>;
  invoice_date: string | null;
  invoice_no: string | null;
  location_id: string | null;
  notes: string | null;
  patient_id: string | null;
  posted_at: Timestamp | null;
  posted_by: string | null;
  prices_include_vat: Generated<boolean>;
  reason: string | null;
  receive_note: string | null;
  receive_status: string | null;
  received_at: Timestamp | null;
  received_by: string | null;
  request_id: string | null;
  reversal_of: string | null;
  reversed_by: string | null;
  status: Generated<string>;
  supplier_id: string | null;
  to_location_id: string | null;
  total_net: Generated<Numeric>;
  total_vat: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  waybill_no: string | null;
  writeoff_reason: string | null;
}

export interface StockItemBarcodes {
  barcode: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  item_id: string;
  kind: Generated<string>;
  pack_id: string | null;
}

export interface StockItemCosts {
  avg_cost: Generated<Numeric>;
  item_id: string;
  qty_on_hand: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  value_on_hand: Generated<Numeric>;
}

export interface StockItemPacks {
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_receipt_default: Generated<boolean>;
  item_id: string;
  name: string;
  qty_base: Numeric;
}

export interface StockItems {
  base_unit: string;
  billing_mode: string | null;
  category_id: string;
  code: Generated<string>;
  country: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expiry_warn_days: number | null;
  generic_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  manufacturer: string | null;
  name: string;
  notes: string | null;
  requires_expiry: Generated<boolean>;
  requires_lot: Generated<boolean>;
  sale_price: Numeric | null;
  serial_tracked: Generated<boolean>;
  storage: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface StockLocations {
  code: string;
  created_at: Generated<Timestamp>;
  department_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: string;
  name: string;
  requires_approval: Generated<boolean>;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface StockLots {
  created_at: Generated<Timestamp>;
  expires_on: string | null;
  first_supplier_id: string | null;
  id: Generated<string>;
  item_id: string;
  lot_no: string | null;
  produced_on: string | null;
  received_qty: Generated<Numeric>;
  received_value: Generated<Numeric>;
  serial_no: string | null;
  status: Generated<string>;
  status_reason: string | null;
  unit_cost: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface StockMoves {
  cost_avg: Numeric | null;
  cost_lot: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_id: string;
  encounter_id: string | null;
  id: Generated<Int8>;
  item_id: string;
  line_id: string | null;
  location_id: string;
  lot_id: string;
  move_type: string;
  patient_id: string | null;
  qty: Numeric;
}

export interface StockRequestLines {
  id: Generated<string>;
  item_id: string;
  line_no: number;
  notes: string | null;
  pack_id: string | null;
  patient_id: string | null;
  qty: Numeric;
  qty_approved: Numeric | null;
  qty_base: Numeric;
  qty_issued: Generated<Numeric>;
  request_id: string;
}

export interface StockRequests {
  approved_at: Timestamp | null;
  approved_by: string | null;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  from_location_id: string;
  id: Generated<string>;
  notes: string | null;
  reason: string | null;
  rejected_at: Timestamp | null;
  rejected_by: string | null;
  req_no: string | null;
  requires_approval: Generated<boolean>;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  to_location_id: string;
  updated_at: Generated<Timestamp>;
  urgent: Generated<boolean>;
}

export interface StockSettings {
  costing_method: Generated<string>;
  id: Generated<number>;
  short_expiry_months: Generated<number>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  writeoff_approval_threshold: Generated<Numeric>;
}

export interface StockSuppliers {
  address: string | null;
  contact_person: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  notes: string | null;
  phone: string | null;
  tax_id: string | null;
  updated_at: Generated<Timestamp>;
  vat_payer: Generated<boolean>;
}

export interface StockUnits {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
}

export interface UserCapabilities {
  capabilities: string[] | null;
  user_id: string | null;
}

export interface UserNotifications {
  body: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  id: Generated<Int8>;
  items: Generated<string[]>;
  kind: string;
  link: string | null;
  read_at: Timestamp | null;
  title: string;
  updated_at: Generated<Timestamp>;
  urgent: Generated<boolean>;
  user_id: string;
}

export interface UserRoles {
  created_at: Generated<Timestamp>;
  role_id: string;
  user_id: string;
}

export interface Users {
  auth_provider: Generated<AuthProvider>;
  consultation_tariff_id: string | null;
  created_at: Generated<Timestamp>;
  department_id: string | null;
  email: string;
  failed_login_count: Generated<number>;
  first_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_section_head: Generated<boolean>;
  last_login_at: Timestamp | null;
  last_name: string;
  ldap_username: string | null;
  license_number: string | null;
  locked_until: Timestamp | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Timestamp | null;
  password_hash: string | null;
  personal_number: string;
  phone: string | null;
  role: string;
  signature_file_path: string | null;
  specialty: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  address_units: AddressUnits;
  allergen_cross_reactivity: AllergenCrossReactivity;
  allergen_group_terms: AllergenGroupTerms;
  allergen_groups: AllergenGroups;
  appointments: Appointments;
  audit_logs: AuditLogs;
  auth_sessions: AuthSessions;
  clinic_settings: ClinicSettings;
  consent_type_versions: ConsentTypeVersions;
  consent_types: ConsentTypes;
  departments: Departments;
  document_counters: DocumentCounters;
  dx_devices: DxDevices;
  dx_images: DxImages;
  dx_item_files: DxItemFiles;
  dx_order_items: DxOrderItems;
  dx_report_templates: DxReportTemplates;
  dx_report_versions: DxReportVersions;
  dx_reports: DxReports;
  dx_services: DxServices;
  encounter_diagnoses: EncounterDiagnoses;
  encounter_payment_overrides: EncounterPaymentOverrides;
  encounter_vitals: EncounterVitals;
  encounters: Encounters;
  endo_procedures: EndoProcedures;
  endo_reprocessing: EndoReprocessing;
  endo_scopes: EndoScopes;
  expenses: Expenses;
  generated_documents: GeneratedDocuments;
  icd10_chapters: Icd10Chapters;
  icd10_codes: Icd10Codes;
  invoice_line_items: InvoiceLineItems;
  invoices: Invoices;
  lab_analytes: LabAnalytes;
  lab_blank_group_assignments: LabBlankGroupAssignments;
  lab_blank_images: LabBlankImages;
  lab_blank_templates: LabBlankTemplates;
  lab_blank_versions: LabBlankVersions;
  lab_delivery_settings: LabDeliverySettings;
  lab_ext_mail: LabExtMail;
  lab_ext_mail_files: LabExtMailFiles;
  lab_ext_mail_state: LabExtMailState;
  lab_ext_settlements: LabExtSettlements;
  lab_ext_shipments: LabExtShipments;
  lab_external_labs: LabExternalLabs;
  lab_gateway_alert_settings: LabGatewayAlertSettings;
  lab_gateway_alerts: LabGatewayAlerts;
  lab_gateway_commands: LabGatewayCommands;
  lab_gateway_state: LabGatewayState;
  lab_instrument_codes: LabInstrumentCodes;
  lab_instrument_messages: LabInstrumentMessages;
  lab_instrument_orders: LabInstrumentOrders;
  lab_instrument_results: LabInstrumentResults;
  lab_instrument_seen_codes: LabInstrumentSeenCodes;
  lab_instruments: LabInstruments;
  lab_methods: LabMethods;
  lab_norm_versions: LabNormVersions;
  lab_qc_materials: LabQcMaterials;
  lab_qc_results: LabQcResults;
  lab_qc_rules: LabQcRules;
  lab_qc_targets: LabQcTargets;
  lab_qc_violations: LabQcViolations;
  lab_reference_ranges: LabReferenceRanges;
  lab_result_deliveries: LabResultDeliveries;
  lab_result_images: LabResultImages;
  lab_results: LabResults;
  lab_specimens: LabSpecimens;
  med_dosage_forms: MedDosageForms;
  med_generic_allergens: MedGenericAllergens;
  med_generics: MedGenerics;
  med_interactions: MedInteractions;
  med_routes: MedRoutes;
  micro_antibiotics: MicroAntibiotics;
  micro_ast: MicroAst;
  micro_cultures: MicroCultures;
  micro_isolates: MicroIsolates;
  micro_organisms: MicroOrganisms;
  micro_panel_items: MicroPanelItems;
  micro_panels: MicroPanels;
  micro_reports: MicroReports;
  path_requests: PathRequests;
  path_specimens: PathSpecimens;
  patient_allergies: PatientAllergies;
  patient_chronic_conditions: PatientChronicConditions;
  patient_consents: PatientConsents;
  patient_files: PatientFiles;
  patients: Patients;
  payments: Payments;
  prescriptions: Prescriptions;
  referral_type_tariffs: ReferralTypeTariffs;
  referrals: Referrals;
  roles: Roles;
  service_tariffs: ServiceTariffs;
  stock_balances: StockBalances;
  stock_categories: StockCategories;
  stock_count_lines: StockCountLines;
  stock_counts: StockCounts;
  stock_doc_lines: StockDocLines;
  stock_docs: StockDocs;
  stock_item_barcodes: StockItemBarcodes;
  stock_item_costs: StockItemCosts;
  stock_item_packs: StockItemPacks;
  stock_items: StockItems;
  stock_locations: StockLocations;
  stock_lots: StockLots;
  stock_moves: StockMoves;
  stock_request_lines: StockRequestLines;
  stock_requests: StockRequests;
  stock_settings: StockSettings;
  stock_suppliers: StockSuppliers;
  stock_units: StockUnits;
  user_capabilities: UserCapabilities;
  user_notifications: UserNotifications;
  user_roles: UserRoles;
  users: Users;
}
