/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentStatus = "cancelled" | "checked_in" | "completed" | "confirmed" | "no_show" | "scheduled";

export type AuthProvider = "ldap" | "local";

export type EncounterStatus = "active" | "cancelled" | "discharged" | "planned";

export type EncounterType = "emergency" | "inpatient" | "outpatient";

export type GenderType = "female" | "male" | "other";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type ReferralStatus = "cancelled" | "completed" | "in_progress" | "requested";

export type ReferralType = "hospitalization" | "imaging" | "lab" | "specialist_consult";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AddressUnits {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  parent_code: string | null;
  region: string;
  type: string;
}

export interface AllergenCrossReactivity {
  group_a: string;
  group_b: string;
}

export interface AllergenGroups {
  code: string;
  name: string;
  needs_review: Generated<boolean>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
}

export interface AllergenGroupTerms {
  group_code: string;
  term: string;
}

export interface Appointments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  department_id: string;
  doctor_id: string;
  encounter_id: string | null;
  id: Generated<string>;
  patient_id: string;
  reason: string | null;
  scheduled_end: Timestamp;
  scheduled_start: Timestamp;
  status: Generated<AppointmentStatus>;
}

export interface AuditLogs {
  action: string;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_name: string;
  id: Generated<Int8>;
  ip_address: string | null;
  new_data: Json | null;
  old_data: Json | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  ip_address: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface ClinicSettings {
  address: string;
  consent_methods: Generated<string[]>;
  director_name: string;
  director_title: Generated<string>;
  email: string | null;
  id: Generated<number>;
  name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ConsentTypes {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  scope: string;
  sort_order: Generated<number>;
}

export interface ConsentTypeVersions {
  body_text: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  text_approved: Generated<boolean>;
  type_code: string;
  version: number;
}

export interface Departments {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface DocumentCounters {
  document_type: string;
  last_value: Generated<number>;
  year: number;
}

export interface DxDevices {
  ae_title: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  modalities: string[];
  name: string;
  room: string | null;
  section: Generated<string>;
  slot_minutes: Generated<number>;
  sort_order: Generated<number>;
  work_end: Generated<string>;
  work_start: Generated<string>;
}

export interface DxOrderItems {
  accession_number: string | null;
  allergy_override_reason: string | null;
  arrived_at: Timestamp | null;
  arrived_by: string | null;
  cancel_reason: string | null;
  clinical_note: string | null;
  collection_issue: string | null;
  collection_issue_at: Timestamp | null;
  contrast_agent: string | null;
  contrast_volume_ml: Numeric | null;
  device_id: string | null;
  dose_text: string | null;
  encounter_id: string;
  id: Generated<string>;
  ordered_at: Generated<Timestamp>;
  ordered_by: string;
  patient_id: string;
  performed_at: Timestamp | null;
  priority: Generated<string>;
  report_text: string | null;
  resulted_at: Timestamp | null;
  resulted_by: string | null;
  safety: Json | null;
  scheduled_by: string | null;
  scheduled_end: Timestamp | null;
  scheduled_start: Timestamp | null;
  section: string;
  service_id: string;
  specimen_id: string | null;
  status: Generated<string>;
  tech_note: string | null;
  technician_id: string | null;
  validated_at: Timestamp | null;
  validated_by: string | null;
}

export interface DxReports {
  amend_reason: string | null;
  amended_at: Timestamp | null;
  amended_by: string | null;
  author_id: string | null;
  created_at: Generated<Timestamp>;
  critical_notified_at: Timestamp | null;
  critical_notified_to: string | null;
  findings: string | null;
  impression: string | null;
  is_critical: Generated<boolean>;
  order_item_id: string;
  recommendation: string | null;
  signed_at: Timestamp | null;
  signed_by: string | null;
  status: Generated<string>;
  technique: string | null;
  template_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DxReportTemplates {
  body: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  findings: string | null;
  id: Generated<string>;
  impression: string | null;
  is_active: Generated<boolean>;
  kind: Generated<string>;
  modality: string | null;
  name: string;
  owner_id: string | null;
  recommendation: string | null;
  section: string;
  service_id: string | null;
  sort_order: Generated<number>;
  target: string | null;
  technique: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DxReportVersions {
  amend_reason: string | null;
  critical_notified_to: string | null;
  findings: string | null;
  id: Generated<string>;
  impression: string;
  is_critical: boolean;
  order_item_id: string;
  recommendation: string | null;
  signed_at: Timestamp;
  signed_by: string;
  technique: string | null;
  version: number;
}

export interface DxServices {
  body_part: string | null;
  code: string;
  container: string | null;
  contrast: string | null;
  duration_minutes: number | null;
  external_lab: string | null;
  group_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  modality: string | null;
  name: string;
  needs_review: Generated<boolean>;
  performed_by: Generated<string>;
  prep_instructions: string | null;
  section: string;
  sort_order: Generated<number>;
  specimen_type: string | null;
  tariff_id: string;
}

export interface EncounterDiagnoses {
  comment: string | null;
  created_at: Generated<Timestamp>;
  diagnosed_by: string | null;
  diagnosis_type: string;
  encounter_id: string;
  icd10_code: string;
  icd10_title: string;
  id: Generated<string>;
}

export interface EncounterPaymentOverrides {
  approved_by: string;
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  reason: string;
}

export interface Encounters {
  attending_doctor_id: string | null;
  chief_complaint: string | null;
  created_at: Generated<Timestamp>;
  department_id: string;
  end_time: Timestamp | null;
  external_referral: string | null;
  history_of_present_illness: string | null;
  id: Generated<string>;
  objective_status: string | null;
  patient_id: string;
  start_time: Generated<Timestamp>;
  status: Generated<EncounterStatus>;
  type: EncounterType;
  updated_at: Generated<Timestamp>;
  visit_kind: Generated<string>;
}

export interface EncounterVitals {
  bmi: Generated<Numeric | null>;
  diastolic_bp: number | null;
  encounter_id: string;
  heart_rate: number | null;
  height_cm: Numeric | null;
  id: Generated<string>;
  recorded_at: Generated<Timestamp>;
  respiratory_rate: number | null;
  spo2: number | null;
  systolic_bp: number | null;
  taken_by: string | null;
  temperature: Numeric | null;
  weight_kg: Numeric | null;
}

export interface GeneratedDocuments {
  document_number: string | null;
  document_type: string;
  encounter_id: string;
  file_path: string;
  file_sha256: string | null;
  generated_at: Generated<Timestamp>;
  generated_by: string | null;
  id: Generated<string>;
  payload: Generated<Json>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  status: Generated<string>;
  verification_token: Generated<string>;
}

export interface Icd10Chapters {
  code_from: string;
  code_to: string;
  id: number;
  title: string;
}

export interface Icd10Codes {
  category: Generated<string | null>;
  chapter_id: number | null;
  code: string;
  is_active: Generated<boolean>;
  is_asterisk: Generated<boolean>;
  is_dagger: Generated<boolean>;
  needs_review: Generated<boolean>;
  title: string;
}

export interface InvoiceLineItems {
  adjusted_by: string | null;
  description: string;
  discount_reason: string | null;
  dx_order_item_id: string | null;
  id: Generated<string>;
  invoice_id: string;
  line_total: Generated<Numeric | null>;
  original_price: Numeric | null;
  quantity: Generated<number>;
  referral_id: string | null;
  tariff_id: string | null;
  unit_price: Numeric;
}

export interface Invoices {
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  insurance_share: Generated<Numeric>;
  invoice_number: string;
  paid_status: Generated<string>;
  patient_share: Numeric;
  state_share: Generated<Numeric>;
  total_amount: Numeric;
}

export interface LabAnalytes {
  code: string;
  critical_high: Numeric | null;
  critical_low: Numeric | null;
  decimals: number | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  options: string | null;
  result_type: string;
  service_id: string;
  sort_order: Generated<number>;
  unit: Generated<string>;
}

export interface LabReferenceRanges {
  age_max_days: Generated<number>;
  age_min_days: Generated<number>;
  analyte_id: string;
  high: Numeric | null;
  id: Generated<string>;
  low: Numeric | null;
  normal_text: string | null;
  sex: string | null;
}

export interface LabResults {
  analyte_id: string;
  entered_at: Generated<Timestamp>;
  entered_by: string | null;
  flag: string | null;
  id: Generated<string>;
  order_item_id: string;
  ref_high: Numeric | null;
  ref_low: Numeric | null;
  ref_text: string | null;
  unit: Generated<string>;
  value_num: Numeric | null;
  value_text: string | null;
}

export interface LabSpecimens {
  barcode: string;
  collected_at: Generated<Timestamp>;
  collected_by: string | null;
  container: string | null;
  encounter_id: string;
  id: Generated<string>;
  patient_id: string;
  received_at: Timestamp | null;
  received_by: string | null;
  reject_reason: string | null;
  specimen_type: string;
  status: Generated<string>;
}

export interface PatientAllergies {
  allergy_type: Generated<string>;
  created_at: Generated<Timestamp>;
  deactivated_reason: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  patient_id: string;
  reaction_type: string | null;
  recorded_by: string | null;
  severity: string;
  substance: string;
}

export interface PatientChronicConditions {
  condition_name: string;
  created_at: Generated<Timestamp>;
  icd10_code: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  patient_id: string;
  recorded_by: string | null;
}

export interface PatientConsents {
  decision: string;
  encounter_id: string | null;
  file_id: string;
  id: Generated<string>;
  method: string;
  patient_id: string;
  recorded_by: string;
  representative_id_number: string | null;
  representative_name: string | null;
  representative_relation: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  signed_at: Generated<Timestamp>;
  signer_type: string;
  type_code: string;
  version_id: string;
}

export interface PatientFiles {
  created_at: Generated<Timestamp>;
  deactivated_reason: string | null;
  doc_type: string;
  file_path: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  mime_type: string;
  note: string | null;
  original_name: string | null;
  patient_id: string;
  sha256: string;
  size_bytes: number;
  uploaded_by: string | null;
}

export interface Patients {
  address: string | null;
  address_country: string | null;
  address_district_code: string | null;
  address_line: string | null;
  address_unit_code: string | null;
  address_village: string | null;
  birth_date: string;
  blood_group: string | null;
  citizenship: Generated<string>;
  created_at: Generated<Timestamp>;
  death_datetime: Timestamp | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  first_name: string;
  gender: GenderType;
  id: Generated<string>;
  is_deceased: Generated<boolean>;
  last_name: string;
  passport_number: string | null;
  personal_number: string | null;
  phone_number: string;
  updated_at: Generated<Timestamp>;
}

export interface Payments {
  amount: Numeric;
  id: Generated<string>;
  invoice_id: string;
  method: string;
  paid_at: Generated<Timestamp>;
  received_by: string | null;
  terminal_ref: string | null;
}

export interface Prescriptions {
  allergy_alert_level: Generated<string>;
  allergy_matches: Json | null;
  allergy_override_by: string | null;
  allergy_override_reason: string | null;
  created_at: Generated<Timestamp>;
  dosage: string;
  duration_days: number | null;
  encounter_id: string;
  frequency: string;
  id: Generated<string>;
  instructions: string | null;
  medication_name: string;
  prescribed_by: string;
  route: string;
}

export interface Referrals {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  encounter_id: string;
  id: Generated<string>;
  reason: string;
  requested_by: string;
  result_text: string | null;
  status: Generated<ReferralStatus>;
  target_department_id: string | null;
  type: ReferralType;
}

export interface ReferralTypeTariffs {
  tariff_id: string;
  type: ReferralType;
}

export interface ServiceTariffs {
  base_price: Numeric;
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  title: string;
}

export interface Users {
  auth_provider: Generated<AuthProvider>;
  consultation_tariff_id: string | null;
  created_at: Generated<Timestamp>;
  department_id: string | null;
  email: string;
  failed_login_count: Generated<number>;
  first_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_section_head: Generated<boolean>;
  last_login_at: Timestamp | null;
  last_name: string;
  ldap_username: string | null;
  license_number: string | null;
  locked_until: Timestamp | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Timestamp | null;
  password_hash: string | null;
  personal_number: string;
  phone: string | null;
  role: string;
  signature_file_path: string | null;
  specialty: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  address_units: AddressUnits;
  allergen_cross_reactivity: AllergenCrossReactivity;
  allergen_group_terms: AllergenGroupTerms;
  allergen_groups: AllergenGroups;
  appointments: Appointments;
  audit_logs: AuditLogs;
  auth_sessions: AuthSessions;
  clinic_settings: ClinicSettings;
  consent_type_versions: ConsentTypeVersions;
  consent_types: ConsentTypes;
  departments: Departments;
  document_counters: DocumentCounters;
  dx_devices: DxDevices;
  dx_order_items: DxOrderItems;
  dx_report_templates: DxReportTemplates;
  dx_report_versions: DxReportVersions;
  dx_reports: DxReports;
  dx_services: DxServices;
  encounter_diagnoses: EncounterDiagnoses;
  encounter_payment_overrides: EncounterPaymentOverrides;
  encounter_vitals: EncounterVitals;
  encounters: Encounters;
  generated_documents: GeneratedDocuments;
  icd10_chapters: Icd10Chapters;
  icd10_codes: Icd10Codes;
  invoice_line_items: InvoiceLineItems;
  invoices: Invoices;
  lab_analytes: LabAnalytes;
  lab_reference_ranges: LabReferenceRanges;
  lab_results: LabResults;
  lab_specimens: LabSpecimens;
  patient_allergies: PatientAllergies;
  patient_chronic_conditions: PatientChronicConditions;
  patient_consents: PatientConsents;
  patient_files: PatientFiles;
  patients: Patients;
  payments: Payments;
  prescriptions: Prescriptions;
  referral_type_tariffs: ReferralTypeTariffs;
  referrals: Referrals;
  service_tariffs: ServiceTariffs;
  users: Users;
}
